OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES    = count_hash.ml
INCDIRS    = ../../lib
LIBDIRS    = ../../lib
LIBS       = pcre
OCAMLFLAGS = -w Aer -strict-sequence
RESULT     = count_hash

-include $(OCAMLMAKEFILE)
