OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES    = cloc.ml
INCDIRS    = ../../lib
LIBDIRS    = ../../lib
LIBS       = pcre
OCAMLFLAGS = -w Aer -strict-sequence
RESULT     = cloc

-include $(OCAMLMAKEFILE)
