OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES    = pcregrep.ml
INCDIRS    = ../../lib
LIBDIRS    = ../../lib
LIBS       = pcre
OCAMLFLAGS = -w Aer -strict-sequence
RESULT     = pcregrep

-include $(OCAMLMAKEFILE)
