OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES    = subst.ml
INCDIRS    = ../../lib
LIBDIRS    = ../../lib
LIBS       = pcre
OCAMLFLAGS = -w Aer -strict-sequence
RESULT     = subst

-include $(OCAMLMAKEFILE)
